name: Amplify Preview URL

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  comment-preview-url:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'feature/')
    steps:
      - name: Get Preview URL
        id: get-url
        run: |
          BRANCH_NAME=$(echo ${{ github.head_ref }} | sed 's/\//-/g')
          # Use specific Amplify app ID for preview URL
          echo "preview_url=https://${BRANCH_NAME}.d18pp8viccmbq.amplifyapp.com" >> $GITHUB_OUTPUT

      - name: Wait for deployment
        run: |
          # Wait for deployment to complete
          sleep 60

      - name: Comment PR
        uses: actions/github-script@v7
        with:
          script: |
            const previewUrl = '${{ steps.get-url.outputs.preview_url }}';
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## 🚀 Preview Environment Ready!\n\n### Preview URL\n${previewUrl}\n\nPlease review the changes.`
            });
