name: Cleanup Preview Environment

on:
  pull_request:
    types: [closed]

jobs:
  notify-cleanup:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'feature/')
    steps:
      - name: Comment PR
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## 🧹 Cleaning Up Preview Environment\n\nThe preview environment will be deleted shortly.`
            });